### ISSUE TITLE
Update PHP version in composer

### ISSUE THREAD

**Issue by pserrer** [belvg-public/Magento2_ApplyTo#1]
Can you update the php version inside the composer.json requirements to support php7.1 (and maybe also 7.2?)

**Comment by hewgim** [comment]
It would be really useful if you could update the composer.json to support php 7.2

**Comment by zyr3x** [comment]
Hi Guys.  Composer.json has been improved

**Comment by hewgim** [comment]
Wow. That was quick!!! Many thanks for that
